/* adapt-e2e-core — C-ABI (Apache-2.0). */

#ifndef ADAPT_E2E_CORE_H
#define ADAPT_E2E_CORE_H

#pragma once

/* GENERATED by cbindgen from adapt-e2e-core. DO NOT EDIT. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Pins the vendored vodozemac serde pickle layout.
 *
 * vodozemac's native pickle carries no format-version integer of its own, so
 * this is a **crate-assigned** constant meaning "the pickle serde shape shipped
 * with the vendored vodozemac revision". Bump it whenever a vendored-rev change
 * alters the pickle shape; the compat-matrix test guards it.
 */
#define ENGINE_VER 1

/**
 * Stable C-ABI return code. **These values are frozen and MUST never be
 * renumbered** — they are part of the committed ABI (`enum e2e_rc`).
 */
enum E2eRc
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  /**
   * Success.
   */
  E2E_RC_OK = 0,
  /**
   * A required pointer argument was NULL.
   */
  E2E_RC_NULL_ARG = -1,
  /**
   * The caller's output buffer was too small (see the two-call convention).
   */
  E2E_RC_SHORT_BUFFER = -2,
  /**
   * A pickled-blob input was malformed or could not be decrypted.
   */
  E2E_RC_BAD_PICKLE = -3,
  /**
   * The pickle envelope had an unknown magic / format / engine version.
   */
  E2E_RC_VERSION = -4,
  /**
   * Message decryption failed (bad MAC, missing/evicted key, etc.).
   */
  E2E_RC_DECRYPT_FAILED = -5,
  /**
   * A supplied seed was the wrong length or otherwise invalid.
   */
  E2E_RC_BAD_SEED = -6,
  /**
   * No one-time key was available to satisfy the request.
   */
  E2E_RC_OTK_EXHAUSTED = -7,
  /**
   * The operation did not match the supplied session/account.
   */
  E2E_RC_SESSION_MISMATCH = -8,
  /**
   * An unexpected internal error occurred.
   */
  E2E_RC_INTERNAL = -98,
  /**
   * A panic was caught at the ABI boundary (defence in depth).
   */
  E2E_RC_PANIC = -99,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum E2eRc E2eRc;
#else
typedef int32_t E2eRc;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Create a new account from `seed`.
 *
 * # Safety
 * All non-NULL pointers must be valid per the two-call convention.
 */
int32_t e2e_account_create(const uint8_t *seed,
                           const uint8_t *pickle_key,
                           uint8_t *out_pickle,
                           size_t *out_pickle_len);

/**
 * Generate `n` one-time keys from `seed`.
 *
 * # Safety
 * All non-NULL pointers must be valid per the two-call convention.
 */
int32_t e2e_account_gen_otks(const uint8_t *in_pickle,
                             size_t in_pickle_len,
                             uint32_t n,
                             const uint8_t *seed,
                             const uint8_t *pickle_key,
                             uint8_t *out_pickle,
                             size_t *out_pickle_len);

/**
 * Generate a fallback key from `seed`.
 *
 * # Safety
 * All non-NULL pointers must be valid per the two-call convention.
 */
int32_t e2e_account_gen_fallback(const uint8_t *in_pickle,
                                 size_t in_pickle_len,
                                 const uint8_t *seed,
                                 const uint8_t *pickle_key,
                                 uint8_t *out_pickle,
                                 size_t *out_pickle_len);

/**
 * Emit the account's public prekey-bundle material. Pure read.
 *
 * # Safety
 * All non-NULL pointers must be valid per the two-call convention.
 */
int32_t e2e_account_bundle(const uint8_t *in_pickle,
                           size_t in_pickle_len,
                           const uint8_t *pickle_key,
                           uint8_t *out_bundle,
                           size_t *out_bundle_len);

/**
 * Create an outbound session. Emits `out_session` and (unchanged)
 * `out_pickle` (account). Both follow the two-call convention.
 *
 * # Safety
 * All non-NULL pointers must be valid per the two-call convention.
 */
int32_t e2e_session_outbound(const uint8_t *in_pickle,
                             size_t in_pickle_len,
                             const uint8_t *ik_b,
                             const uint8_t *otk_b,
                             const uint8_t *seed,
                             const uint8_t *pickle_key,
                             uint8_t *out_session,
                             size_t *out_session_len,
                             uint8_t *out_pickle,
                             size_t *out_pickle_len);

/**
 * Establish an inbound session from a pre-key message. Emits
 * `out_session`, the mutated `out_pickle` (account, OTK removed), and the
 * decrypted first-message `out_pt`. All follow the two-call convention.
 *
 * # Safety
 * All non-NULL pointers must be valid per the two-call convention.
 */
int32_t e2e_session_inbound(const uint8_t *in_pickle,
                            size_t in_pickle_len,
                            const uint8_t *ik_a,
                            const uint8_t *prekey_msg,
                            size_t prekey_msg_len,
                            const uint8_t *pickle_key,
                            uint8_t *out_session,
                            size_t *out_session_len,
                            uint8_t *out_pickle,
                            size_t *out_pickle_len,
                            uint8_t *out_pt,
                            size_t *out_pt_len);

/**
 * Encrypt `pt`. Draws `seed` only on a DH-ratchet advance. Emits the
 * message body (`out_msg`), its type (`out_msg_type`: 0=pre-key, 1=normal), and
 * the advanced session (`out_session`).
 *
 * # Safety
 * All non-NULL pointers must be valid per the two-call convention.
 */
int32_t e2e_encrypt(const uint8_t *in_session,
                    size_t in_session_len,
                    const uint8_t *pt,
                    size_t pt_len,
                    const uint8_t *seed,
                    const uint8_t *pickle_key,
                    uint8_t *out_msg,
                    size_t *out_msg_len,
                    uint32_t *out_msg_type,
                    uint8_t *out_session,
                    size_t *out_session_len);

/**
 * Decrypt a message. Draws no entropy. Emits plaintext + advanced
 * session.
 *
 * # Safety
 * All non-NULL pointers must be valid per the two-call convention.
 */
int32_t e2e_decrypt(const uint8_t *in_session,
                    size_t in_session_len,
                    uint32_t msg_type,
                    const uint8_t *msg,
                    size_t msg_len,
                    const uint8_t *pickle_key,
                    uint8_t *out_pt,
                    size_t *out_pt_len,
                    uint8_t *out_session,
                    size_t *out_session_len);

/**
 * Write the session's 32-byte id into `out_id[32]`.
 *
 * # Safety
 * `out_id` must be valid for writes of 32 bytes.
 */
int32_t e2e_session_id(const uint8_t *in_session,
                       size_t in_session_len,
                       const uint8_t *pickle_key,
                       uint8_t *out_id);

/**
 * Write 1 into `*out_bool` if the session pickle corresponds to the
 * session the pre-key message would establish (idempotent re-delivery
 * detection), else 0.
 *
 * # Safety
 * All non-NULL pointers must be valid; `out_bool` must be a valid `*mut u32`.
 */
int32_t e2e_matches_inbound(const uint8_t *in_pickle,
                            size_t in_pickle_len,
                            const uint8_t *prekey_msg,
                            size_t prekey_msg_len,
                            const uint8_t *pickle_key,
                            uint32_t *out_bool);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* ADAPT_E2E_CORE_H */
